// ignore_for_file: non_constant_identifier_names, file_names, unused_import

import 'dart:convert';
import 'dart:ui';

import 'package:flutter/material.dart';
import 'package:sise/helpers/collection_helper.dart';

class SousProjet {
  int id;
  String name;
  int id_commune;
  String? commune;
  int id_district;
  String? district;
  int id_region;
  String? region;
  String? fokontany;
  String? type_travaux;
  int? id_infrastructure;
  String? infrastructure;
  int? id_secteur;
  String? secteur;
  String? categorie;
  String? composante;
  String? montant_prev;
  String? date_convention;
  String? date_virement;
  String? geolocalisation;
  String? numero_conv;
  String? ami_date;
  String? ami_photo;
  String? be_date;
  String? be_photo;
  String? osbe_date;
  String? osbe_photo;
  String? nom_be;
  String? montant_becontrat;
  String? retenue;
  String? fes_date;
  String? fes_faisabilite;
  String? aps_date;
  String? aps_photo;
  String? apd_date;
  String? apd_photo;
  String? dao_date;
  String? dao_photo;
  String? lao_date;
  String? lao_photo;
  String? nom_entreprise;
  String? montant_entcontrat;
  String? ce_date;
  String? ce_photo;
  String? ose_date;
  String? ose_photo;
  String? dem_date;
  String? dem_date_prev;
  String? dem_photo;
  String? duree_travaux;
  String? recep_date;
  String? recep_prov_date;
  String? recep_date_prev;
  String? recep_prov_date_prev;
  String? recepdef_date_prev;
  String? recepdef_date;
  String? longitude;
  String? latitude;
  String? cpgu;
  String? situation;
  String? prochaine;

  static const String model = 'a.sise.sousprojet';
  static const List<String> fields = [
    'id',
    '__last_update',
    'name',
    'id_commune',
    'id_district',
    'id_region',
    'fokontany',
    'id_infrastructure',
    'id_secteur',
    'type_travaux',
    'categorie',
    'composante',
    'montant_prev',
    'date_convention',
    'date_virement',
    'geolocalisation',
    'numero_conv',
    'ami_date',
    'ami_photo',
    'be_date',
    'be_photo',
    'osbe_date',
    'osbe_photo',
    'nom_be',
    'montant_becontrat',
    'retenue',
    'fes_date',
    'fes_faisabilite',
    'aps_date',
    'aps_photo',
    'apd_date',
    'apd_photo',
    'dao_date',
    'dao_photo',
    'lao_date',
    'lao_photo',
    'nom_entreprise',
    'montant_entcontrat',
    'ce_date',
    'ce_photo',
    'ose_date',
    'ose_photo',
    'dem_date',
    'dem_date_prev',
    'dem_photo',
    'duree_travaux',
    'recep_date',
    'recep_prov_date',
    'recep_date_prev',
    'recep_prov_date_prev',
    'recepdef_date_prev',
    'recepdef_date',
    'longitude',
    'latitude',
    'cpgu',
    'situation',
    'prochaine'
  ];

  SousProjet({
    required this.id,
    required this.name,
    required this.id_commune,
    required this.id_district,
    required this.id_region,
    this.fokontany,
    this.commune,
    this.district,
    this.region,
    this.id_infrastructure,
    this.infrastructure,
    this.id_secteur,
    this.type_travaux,
    this.secteur,
    this.categorie,
    this.composante,
    this.montant_prev,
    this.date_convention,
    this.date_virement,
    this.geolocalisation,
    this.numero_conv,
    this.ami_date,
    this.ami_photo,
    this.be_date,
    this.be_photo,
    this.osbe_date,
    this.osbe_photo,
    this.nom_be,
    this.montant_becontrat,
    this.retenue,
    this.fes_date,
    this.fes_faisabilite,
    this.aps_date,
    this.aps_photo,
    this.apd_date,
    this.apd_photo,
    this.dao_date,
    this.dao_photo,
    this.lao_date,
    this.lao_photo,
    this.nom_entreprise,
    this.montant_entcontrat,
    this.ce_date,
    this.ce_photo,
    this.ose_date,
    this.ose_photo,
    this.dem_date,
    this.dem_date_prev,
    this.dem_photo,
    this.duree_travaux,
    this.recep_date,
    this.recep_prov_date,
    this.recep_date_prev,
    this.recep_prov_date_prev,
    this.recepdef_date_prev,
    this.recepdef_date,
    this.longitude,
    this.latitude,
    this.cpgu,
    this.situation,
    this.prochaine,
  });

  SousProjet.fromJson(Map<String, dynamic> json)
      : id = json['id'],
        name = json['name'],
        id_commune = json['id_commune'][0],
        id_district = json['id_district'][0],
        id_region = json['id_region'][0],
        fokontany = json['fokontany'] != false ? json['fokontany'] : '',
        id_infrastructure = json['id_infrastructure'] != false
            ? json['id_infrastructure'][0]
            : null,
        id_secteur = json['id_secteur'] != false ? json['id_secteur'][0] : null,
        categorie = json['categorie'] != false ? json['categorie'] : '',
        composante = json['composante'] != false ? json['composante'] : '',
        type_travaux =
            json['type_travaux'] != false ? json['type_travaux'] : '',
        montant_prev = json['montant_prev'].toString(),
        date_convention =
            json['date_convention'] != false ? json['date_convention'] : '',
        date_virement =
            json['date_virement'] != false ? json['date_virement'] : '',
        geolocalisation =
            json['geolocalisation'] != false ? json['geolocalisation'] : '',
        numero_conv = json['numero_conv'] != false ? json['numero_conv'] : '',
        ami_date = json['ami_date'] != false ? json['ami_date'] : '',
        ami_photo = json['ami_photo'] != false ? json['ami_photo'] : null,
        be_date = json['be_date'] != false ? json['be_date'] : '',
        be_photo = json['be_photo'] != false ? json['be_photo'] : null,
        osbe_date = json['osbe_date'] != false ? json['osbe_date'] : '',
        osbe_photo = json['osbe_photo'] != false ? json['osbe_photo'] : null,
        nom_be = json['nom_be'] != false ? json['nom_be'] : '',
        montant_becontrat = json['montant_becontrat'].toString(),
        retenue = json['retenue'] != false ? json['retenue'] : '',
        fes_date = json['fes_date'] != false ? json['fes_date'] : '',
        fes_faisabilite =
            json['fes_faisabilite'] != false ? json['fes_faisabilite'] : '',
        aps_date = json['aps_date'] != false ? json['aps_date'] : '',
        aps_photo = json['aps_photo'] != false ? json['aps_photo'] : null,
        apd_date = json['apd_date'] != false ? json['apd_date'] : '',
        apd_photo = json['apd_photo'] != false ? json['apd_photo'] : null,
        dao_date = json['dao_date'] != false ? json['dao_date'] : '',
        dao_photo = json['dao_photo'] != false ? json['dao_photo'] : null,
        lao_date = json['lao_date'] != false ? json['lao_date'] : '',
        lao_photo = json['lao_photo'] != false ? json['lao_photo'] : null,
        nom_entreprise =
            json['nom_entreprise'] != false ? json['nom_entreprise'] : '',
        montant_entcontrat = json['montant_entcontrat'].toString(),
        ce_date = json['ce_date'] != false ? json['ce_date'] : '',
        ce_photo = json['ce_photo'] != false ? json['ce_photo'] : null,
        ose_date = json['ose_date'] != false ? json['ose_date'] : '',
        ose_photo = json['ose_photo'] != false ? json['ose_photo'] : null,
        dem_date = json['dem_date'] != false ? json['dem_date'] : '',
        dem_date_prev =
            json['dem_date_prev'] != false ? json['dem_date_prev'] : '',
        dem_photo = json['dem_photo'] != false ? json['dem_photo'] : null,
        duree_travaux = json['duree_travaux'].toString(),
        recep_date = json['recep_date'] != false ? json['recep_date'] : '',
        recep_prov_date =
            json['recep_prov_date'] != false ? json['recep_prov_date'] : '',
        recep_date_prev =
            json['recep_date_prev'] != false ? json['recep_date_prev'] : '',
        recep_prov_date_prev = json['recep_prov_date_prev'] != false
            ? json['recep_prov_date_prev']
            : '',
        recepdef_date_prev = json['recepdef_date_prev'] != false
            ? json['recepdef_date_prev']
            : '',
        recepdef_date =
            json['recepdef_date'] != false ? json['recepdef_date'] : '',
        longitude = json['longitude'].toString(),
        latitude = json['latitude'].toString(),
        cpgu = json['cpgu'] != false ? json['cpgu'] : '',
        situation = json['situation'] != false ? json['situation'] : '',
        prochaine = json['prochaine'] != false ? json['prochaine'] : '';

  factory SousProjet.fromJsonSqlite(String jsonStr) {
    final Map<String, dynamic> json = jsonDecode(jsonStr);
    return SousProjet(
      id: json['id'],
      name: json['name'],
      id_commune: json['id_commune'],
      id_district: json['id_district'],
      id_region: json['id_region'],
      commune: json['commune'],
      district: json['district'],
      region: json['region'],
      fokontany: json['fokontany'],
      id_infrastructure: json['id_infrastructure'],
      id_secteur: json['id_secteur'],
      type_travaux: json['type_travaux'],
      categorie: json['categorie'],
      composante: json['composante'],
      montant_prev: json['montant_prev'],
      date_convention: json['date_convention'],
      date_virement: json['date_virement'],
      geolocalisation: json['geolocalisation'],
      numero_conv: json['numero_conv'],
      ami_date: json['ami_date'],
      ami_photo: json['ami_photo'],
      be_date: json['be_date'],
      be_photo: json['be_photo'],
      osbe_date: json['osbe_date'],
      osbe_photo: json['osbe_photo'],
      nom_be: json['nom_be'],
      montant_becontrat: json['montant_becontrat'],
      retenue: json['retenue'],
      fes_date: json['fes_date'],
      fes_faisabilite: json['fes_faisabilite'],
      aps_date: json['aps_date'],
      aps_photo: json['aps_photo'],
      apd_date: json['apd_date'],
      apd_photo: json['apd_photo'],
      dao_date: json['dao_date'],
      dao_photo: json['dao_photo'],
      lao_date: json['lao_date'],
      lao_photo: json['lao_photo'],
      nom_entreprise: json['nom_entreprise'],
      montant_entcontrat: json['montant_entcontrat'],
      ce_date: json['ce_date'],
      ce_photo: json['ce_photo'],
      ose_date: json['ose_date'],
      ose_photo: json['ose_photo'],
      dem_date: json['dem_date'],
      dem_date_prev: json['dem_date_prev'],
      dem_photo: json['dem_photo'],
      duree_travaux: json['duree_travaux'],
      recep_date: json['recep_date'],
      recep_prov_date: json['recep_prov_date'],
      recep_date_prev: json['recep_date_prev'],
      recep_prov_date_prev: json['recep_prov_date_prev'],
      recepdef_date_prev: json['recepdef_date_prev'],
      recepdef_date: json['recepdef_date'],
      longitude: json['longitude'],
      latitude: json['latitude'],
      cpgu: json['cpgu'],
      situation: json['situation'],
      prochaine: json['prochaine'],
    );
  }

  SousProjet.fromJsonLocal(Map<String, dynamic> json)
      : id = json['id'],
        name = json['name'],
        fokontany = json['fokontany'],
        id_commune = json['id_commune'],
        commune = json['commune'],
        id_district = json['id_district'],
        district = json['district'],
        id_region = json['id_region'],
        region = json['region'],
        id_infrastructure = json['id_infrastructure'],
        infrastructure = json['infrastructure'],
        id_secteur = json['id_secteur'],
        secteur = json['secteur'],
        type_travaux = json['type_travaux'],
        categorie = json['categorie'],
        composante = json['composante'],
        montant_prev = json['montant_prev'],
        date_convention = json['date_convention'],
        date_virement = json['date_virement'],
        geolocalisation = json['geolocalisation'],
        numero_conv = json['numero_conv'],
        ami_date = json['ami_date'],
        ami_photo = json['ami_photo'],
        be_date = json['be_date'],
        be_photo = json['be_photo'],
        osbe_date = json['osbe_date'],
        osbe_photo = json['osbe_photo'],
        nom_be = json['nom_be'],
        montant_becontrat = json['montant_becontrat'],
        retenue = json['retenue'],
        fes_date = json['fes_date'],
        fes_faisabilite = json['fes_faisabilite'],
        aps_date = json['aps_date'],
        aps_photo = json['aps_photo'],
        apd_date = json['apd_date'],
        apd_photo = json['apd_photo'],
        dao_date = json['dao_date'],
        dao_photo = json['dao_photo'],
        lao_date = json['lao_date'],
        lao_photo = json['lao_photo'],
        nom_entreprise = json['nom_entreprise'],
        montant_entcontrat = json['montant_entcontrat'],
        ce_date = json['ce_date'],
        ce_photo = json['ce_photo'],
        ose_date = json['ose_date'],
        ose_photo = json['ose_photo'],
        dem_date = json['dem_date'],
        dem_date_prev = json['dem_date_prev'],
        dem_photo = json['dem_photo'],
        duree_travaux = json['duree_travaux'],
        recep_date = json['recep_date'],
        recep_prov_date = json['recep_prov_date'],
        recep_date_prev = json['recep_date_prev'],
        recep_prov_date_prev = json['recep_prov_date_prev'],
        recepdef_date_prev = json['recepdef_date_prev'],
        recepdef_date = json['recepdef_date'],
        longitude = json['longitude'],
        latitude = json['latitude'],
        cpgu = json['cpgu'],
        situation = json['situation'],
        prochaine = json['prochaine'];

  static fromJsonArray(List json) {
    return json.map((e) => SousProjet.fromJson(e)).toList();
  }

  Map<String, dynamic> toJson() {
    return {
      'id': id,
      'name': name,
      'id_commune': id_commune,
      'commune': commune,
      'id_district': id_district,
      'district': district,
      'id_region': id_region,
      'region': region,
      'fokontany': fokontany,
      'id_infrastructure': id_infrastructure,
      'infrastructure': infrastructure,
      'id_secteur': id_secteur,
      'secteur': secteur,
      'type_travaux': type_travaux,
      'categorie': categorie,
      'composante': composante,
      'montant_prev': montant_prev,
      'date_convention': date_convention,
      'date_virement': date_virement,
      'geolocalisation': geolocalisation,
      'numero_conv': numero_conv,
      'ami_date': ami_date,
      'ami_photo': ami_photo,
      'be_date': be_date,
      'be_photo': be_photo,
      'osbe_date': osbe_date,
      'osbe_photo': osbe_photo,
      'nom_be': nom_be,
      'montant_becontrat': montant_becontrat,
      'retenue': retenue,
      'fes_date': fes_date,
      'fes_faisabilite': fes_faisabilite,
      'aps_date': aps_date,
      'aps_photo': aps_photo,
      'apd_date': apd_date,
      'apd_photo': apd_photo,
      'dao_date': dao_date,
      'dao_photo': dao_photo,
      'lao_date': lao_date,
      'lao_photo': lao_photo,
      'nom_entreprise': nom_entreprise,
      'montant_entcontrat': montant_entcontrat,
      'ce_date': ce_date,
      'ce_photo': ce_photo,
      'ose_date': ose_date,
      'ose_photo': ose_photo,
      'dem_date': dem_date,
      'dem_date_prev': dem_date_prev,
      'dem_photo': dem_photo,
      'duree_travaux': duree_travaux,
      'recep_date': recep_date,
      'recep_prov_date': recep_prov_date,
      'recep_date_prev': recep_date_prev,
      'recep_prov_date_prev': recep_prov_date_prev,
      'recepdef_date_prev': recepdef_date_prev,
      'recepdef_date': recepdef_date,
      'longitude': longitude,
      'latitude': latitude,
      'cpgu': cpgu,
      'situation': situation,
      'prochaine': prochaine,
    };
  }

  Map<String, dynamic> toJsonSqlite() {
    return {
      'id': id,
      'name': name,
      'id_commune': id_commune,
      // 'commune': commune,
      'id_district': id_district,
      // 'district': district,
      'id_region': id_region,
      // 'region': region,
      'fokontany': fokontany,
      'id_infrastructure': id_infrastructure,
      // 'infrastructure': infrastructure,
      'id_secteur': id_secteur,
      // 'secteur': secteur,
      'categorie': categorie,
      'composante': composante,
      'type_travaux': type_travaux,
      'montant_prev': montant_prev,
      'date_convention': date_convention,
      'date_virement': date_virement,
      'geolocalisation': geolocalisation,
      'numero_conv': numero_conv,
      'ami_date': ami_date,
      'ami_photo': null,
      'be_date': be_date,
      'be_photo': null,
      'osbe_date': osbe_date,
      'osbe_photo': null,
      'nom_be': nom_be,
      'montant_becontrat': montant_becontrat,
      'retenue': retenue,
      'fes_date': fes_date,
      'fes_faisabilite': fes_faisabilite,
      'aps_date': aps_date,
      'aps_photo': null,
      'apd_date': apd_date,
      'apd_photo': null,
      'dao_date': dao_date,
      'dao_photo': null,
      'lao_date': lao_date,
      'lao_photo': null,
      'nom_entreprise': nom_entreprise,
      'montant_entcontrat': montant_entcontrat,
      'ce_date': ce_date,
      'ce_photo': null,
      'ose_date': ose_date,
      'ose_photo': null,
      'dem_date': dem_date,
      'dem_date_prev': dem_date_prev,
      'dem_photo': null,
      'duree_travaux': duree_travaux,
      'recep_date': recep_date,
      'recep_prov_date': recep_prov_date,
      'recep_date_prev': recep_date_prev,
      'recep_prov_date_prev': recep_prov_date_prev,
      'recepdef_date_prev': recepdef_date_prev,
      'recepdef_date': recepdef_date,
      'longitude': longitude,
      'latitude': latitude,
      'cpgu': cpgu,
      'situation': situation,
      'prochaine': prochaine,
    };
  }

  @override
  String toString() {
    return jsonEncode(toJson());
  }

  SousProjet.fromMap(Map<String, dynamic> map)
      : id = map['id'],
        name = map['name'],
        id_commune = map['id_commune'],
        id_district = map['id_district'],
        id_region = map['id_region'],
        commune = map['commune'],
        district = map['district'],
        region = map['region'],
        fokontany = map['fokontany'],
        id_infrastructure = map['id_infrastructure'],
        infrastructure = map['infrastructure'],
        id_secteur = map['id_secteur'],
        secteur = map['secteur'],
        type_travaux = map['type_travaux'],
        categorie = map['categorie'],
        composante = map['composante'],
        montant_prev = map['montant_prev'].toString(),
        date_convention = map['date_convention'],
        date_virement = map['date_virement'],
        geolocalisation = map['geolocalisation'],
        numero_conv = map['numero_conv'],
        ami_date = map['ami_date'],
        ami_photo = map['ami_photo'],
        be_date = map['be_date'],
        be_photo = map['be_photo'],
        osbe_date = map['osbe_date'],
        osbe_photo = map['osbe_photo'],
        nom_be = map['nom_be'],
        montant_becontrat = map['montant_becontrat'].toString(),
        retenue = map['retenue'],
        fes_date = map['fes_date'],
        fes_faisabilite = map['fes_faisabilite'],
        aps_date = map['aps_date'],
        aps_photo = map['aps_photo'],
        apd_date = map['apd_date'],
        apd_photo = map['apd_photo'],
        dao_date = map['dao_date'],
        dao_photo = map['dao_photo'],
        lao_date = map['lao_date'],
        lao_photo = map['lao_photo'],
        nom_entreprise = map['nom_entreprise'],
        montant_entcontrat = map['montant_entcontrat'].toString(),
        ce_date = map['ce_date'],
        ce_photo = map['ce_photo'],
        ose_date = map['ose_date'],
        ose_photo = map['ose_photo'],
        dem_date = map['dem_date'],
        duree_travaux = map['duree_travaux'].toString(),
        dem_date_prev = map['dem_date_prev'],
        dem_photo = map['dem_photo'],
        recep_date = map['recep_date'],
        recep_prov_date = map['recep_prov_date'],
        recep_date_prev = map['recep_date_prev'],
        recep_prov_date_prev = map['recep_prov_date_prev'],
        recepdef_date_prev = map['recepdef_date_prev'],
        recepdef_date = map['recepdef_date'],
        longitude = map['longitude'].toString(),
        latitude = map['latitude'].toString(),
        cpgu = map['cpgu'],
        situation = map['situation'],
        prochaine = map['prochaine'];

  SousProjet.fromMapDatabase(Map<String, dynamic> map)
      : id = map['id'],
        name = map['name'],
        id_commune = map['id_commune'],
        id_district = map['id_district'],
        id_region = map['id_region'],
        commune = map['commune'],
        district = map['district'],
        region = map['region'],
        fokontany = map['fokontany'],
        id_infrastructure = map['id_infrastructure'],
        infrastructure = map['infrastructure'],
        id_secteur = map['id_secteur'],
        secteur = map['secteur'],
        type_travaux = map['type_travaux'],
        categorie = map['categorie'],
        composante = map['composante'],
        montant_prev = map['montant_prev'].toString(),
        date_convention = map['date_convention'],
        date_virement = map['date_virement'],
        geolocalisation = map['geolocalisation'],
        numero_conv = map['numero_conv'],
        ami_date = map['ami_date'],
        ami_photo = map['ami_photo'],
        be_date = map['be_date'],
        be_photo = map['be_photo'],
        osbe_date = map['osbe_date'],
        osbe_photo = map['osbe_photo'],
        nom_be = map['nom_be'],
        montant_becontrat = map['montant_becontrat'].toString(),
        retenue = map['retenue'],
        fes_date = map['fes_date'],
        fes_faisabilite = map['fes_faisabilite'],
        aps_date = map['aps_date'],
        aps_photo = map['aps_photo'],
        apd_date = map['apd_date'],
        apd_photo = map['apd_photo'],
        dao_date = map['dao_date'],
        dao_photo = map['dao_photo'],
        lao_date = map['lao_date'],
        lao_photo = map['lao_photo'],
        nom_entreprise = map['nom_entreprise'],
        montant_entcontrat = map['montant_entcontrat'].toString(),
        ce_date = map['ce_date'],
        ce_photo = map['ce_photo'],
        ose_date = map['ose_date'],
        ose_photo = map['ose_photo'],
        dem_date = map['dem_date'],
        dem_date_prev = map['dem_date_prev'],
        dem_photo = map['dem_photo'],
        duree_travaux = map['duree_travaux'].toString(),
        recep_date = map['recep_date'],
        recep_prov_date = map['recep_prov_date'],
        recep_date_prev = map['recep_date_prev'],
        recep_prov_date_prev = map['recep_prov_date_prev'],
        recepdef_date_prev = map['recepdef_date_prev'],
        recepdef_date = map['recepdef_date'],
        longitude = map['longitude'].toString(),
        latitude = map['latitude'].toString(),
        cpgu = map['cpgu'],
        situation = map['situation'],
        prochaine = map['prochaine'];

  Map<String, dynamic> toMap() {
    var map = <String, dynamic>{
      'id': id,
      'name': name,
      'id_commune': id_commune,
      'id_district': id_district,
      'id_region': id_region,
      'fokontany': fokontany,
      'id_infrastructure': id_infrastructure,
      // 'infrastructure': infrastructure,
      'id_secteur': id_secteur,
      // 'secteur': secteur,
      'type_travaux': type_travaux,
      'categorie': categorie,
      'composante': composante,
      'montant_prev': montant_prev,
      'date_convention': date_convention,
      'date_virement': date_virement,
      'geolocalisation': geolocalisation,
      'numero_conv': numero_conv,
      'ami_date': ami_date,
      'ami_photo': ami_photo,
      'be_date': be_date,
      'be_photo': be_photo,
      'osbe_date': osbe_date,
      'osbe_photo': osbe_photo,
      'nom_be': nom_be,
      'montant_becontrat': montant_becontrat,
      'retenue': retenue,
      'fes_date': fes_date,
      'fes_faisabilite': fes_faisabilite,
      'aps_date': aps_date,
      'aps_photo': aps_photo,
      'apd_date': apd_date,
      'apd_photo': apd_photo,
      'dao_date': dao_date,
      'dao_photo': dao_photo,
      'lao_date': lao_date,
      'lao_photo': lao_photo,
      'nom_entreprise': nom_entreprise,
      'montant_entcontrat': montant_entcontrat,
      'ce_date': ce_date,
      'ce_photo': ce_photo,
      'ose_date': ose_date,
      'ose_photo': ose_photo,
      'dem_date': dem_date,
      'dem_date_prev': dem_date_prev,
      'dem_photo': dem_photo,
      'duree_travaux': duree_travaux,
      'recep_date': recep_date,
      'recep_prov_date': recep_prov_date,
      'recep_date_prev': recep_date_prev,
      'recep_prov_date_prev': recep_prov_date_prev,
      'recepdef_date_prev': recepdef_date_prev,
      'recepdef_date': recepdef_date,
      'longitude': longitude,
      'latitude': latitude,
      'cpgu': cpgu,
      'situation': situation,
      'prochaine': prochaine,
    };
    return map;
  }
}
